# This workflow will build sdist & bdist of Python Package with specific python version.

name: Build Distribution ğŸ“¦

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build_dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9']

    steps:
    - name: check out repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Set up Python ğŸ ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Build Python ğŸ distribution ğŸ“¦
      run: |
        python -m pip install build --user
        python -m build

    - name: Upload distribution ğŸ“¦ as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-python${{ matrix.python }}
        path: dist/*
